/** Declaration file generated by dts-gen */
declare module "serverless-slack" {
	import { AxiosInstance, AxiosResponse } from "axios";

	export namespace Store {
		function get(id: any): any;

		function query(method: any, params: any): any;

		function save(data: any): any;
	}

	export interface Bot {
		api: AxiosInstance;
		getData: <T = any>(response: AxiosResponse) => T;
		reply: (messageOrPayload: string | object) => void;
		replyPrivate: (messageOrPayload: string | object) => void;
	}

	export type Listener<T> = (message: T, bot: Bot) => void;

	export function on<T = any>(type: string, listener: Listener<T>): any;

	export function handler(...args: any[]): void;
}
